import {
	VscBook,
	VscDebugStepInto,
	VscDebugStepOut,
	VscLayers,
	VscOrganization,
	VscPlay,
	VscShield,
	VscSymbolBoolean,
	VscSymbolClass,
	VscSymbolEvent,
	VscSymbolMethod,
	VscSymbolNamespace,
	VscSymbolVariable,
	VscTypeHierarchy,
} from "react-icons/vsc";

export const Icons = {
	Domain: <VscOrganization />,
	Subdomain: <VscLayers />,
	BoundedContext: <VscSymbolVariable />,
	Aggregate: <VscSymbolClass />,
	Entity: <VscSymbolMethod />,
	ValueObject: <VscSymbolNamespace />,
	Events: <VscSymbolEvent />,
	Operations: <VscPlay />,
	Invariants: <VscShield />,
	Policy: <VscSymbolBoolean />,
	Term: <VscBook />,
	Service: <VscTypeHierarchy />,
	Provider: <VscDebugStepInto />,
	Consumer: <VscDebugStepOut />,
};
