/**
 * Build-time generation for the skill bundle.
 *
 * - `generateReferences()` renders `references/model-reference.md` and
 *   `references/validation-rules.md` from the core package's build output, so
 *   the skill can never describe a model that core does not implement.
 * - `writeBundle()` embeds every file under `skill/` into
 *   `src/bundle.generated.ts`, so consumers (the VS Code extension included)
 *   read the bundle from the library without touching node_modules.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
export const packageRoot = join(here, "..");
export const skillRoot = join(packageRoot, "skill");

const corePkg = dirname(
	require.resolve("@open-domain-specification/core/package.json"),
);
// No version in the header: the build must leave the committed files untouched
// across a version bump, or lerna refuses to publish on a dirty tree.
const GENERATED_HEADER = (source: string) =>
	`<!-- Generated by packages/skill/scripts/generate.mts from @open-domain-specification/core (${source}); do not edit. -->\n`;

// ---------------------------------------------------------------------------
// model-reference.md
// ---------------------------------------------------------------------------

type JsonSchema = {
	title?: string;
	description?: string;
	type?: string;
	enum?: string[];
	properties?: Record<string, JsonSchema>;
	required?: string[];
	items?: JsonSchema;
	additionalProperties?: boolean | JsonSchema;
	anyOf?: JsonSchema[];
	$ref?: string;
};

function refName(ref: string): string {
	return ref.replace("#/definitions/", "");
}

function isRefObject(schema: JsonSchema): boolean {
	return (
		schema.type === "object" &&
		!!schema.properties &&
		Object.keys(schema.properties).length === 1 &&
		"$ref" in schema.properties
	);
}

/** A compact type expression for one property. */
function typeOf(schema: JsonSchema, defs: Record<string, JsonSchema>): string {
	if (schema.$ref) {
		const name = refName(schema.$ref);
		const target = defs[name];
		if (target?.enum) return target.enum.map((v) => `"${v}"`).join(" | ");
		const shown = name.replace(/Schema$/, "");
		return `[${shown}](#${shown.toLowerCase()})`;
	}
	if (schema.enum) return schema.enum.map((v) => `"${v}"`).join(" | ");
	if (schema.anyOf) return schema.anyOf.map((s) => typeOf(s, defs)).join(" | ");
	if (isRefObject(schema)) return '`{ "$ref": string }`';
	if (schema.type === "array")
		return `array of ${typeOf(schema.items ?? {}, defs)}`;
	if (
		schema.type === "object" &&
		schema.additionalProperties &&
		typeof schema.additionalProperties === "object"
	)
		return `map of id to ${typeOf(schema.additionalProperties, defs)}`;
	return schema.type ?? "unknown";
}

function oneLine(text?: string): string {
	return (text ?? "").replace(/\s*\n\s*/g, " ").trim();
}

function renderObject(
	name: string,
	schema: JsonSchema,
	defs: Record<string, JsonSchema>,
): string {
	const lines: string[] = [`## ${name}`, ""];
	if (schema.description) lines.push(oneLine(schema.description), "");
	if (schema.anyOf) {
		lines.push(
			`One of: ${schema.anyOf.map((s) => typeOf(s, defs)).join(", ")}.`,
			"",
		);
		return lines.join("\n");
	}
	const required = new Set(schema.required ?? []);
	lines.push("| Field | Type | Required | Notes |", "|---|---|---|---|");
	for (const [field, prop] of Object.entries(schema.properties ?? {})) {
		lines.push(
			`| \`${field}\` | ${typeOf(prop, defs)} | ${required.has(field) ? "yes" : "no"} | ${oneLine(prop.description)} |`,
		);
	}
	lines.push("");
	if (schema.additionalProperties === false)
		lines.push("No other fields are allowed.", "");
	return lines.join("\n");
}

const REF_GRAMMAR = `## Ref grammar

Every cross-link is an object \`{ "$ref": "<path>" }\`. Paths are JSON pointers into the workspace, built from the ids that key each collection:

| Element | Path |
|---|---|
| Team | \`#/teams/<team>\` |
| Domain | \`#/domains/<domain>\` |
| Subdomain | \`#/domains/<domain>/subdomains/<subdomain>\` |
| Bounded context | \`#/boundedcontexts/<bc>\` |
| Aggregate | \`#/boundedcontexts/<bc>/aggregates/<aggregate>\` |
| Entity | \`#/boundedcontexts/<bc>/aggregates/<aggregate>/entities/<entity>\` |
| Value object | \`#/boundedcontexts/<bc>/valueobjects/<vo>\` |
| Invariant of an aggregate | \`#/boundedcontexts/<bc>/aggregates/<aggregate>/invariants/<invariant>\` |
| Invariant of a context | \`#/boundedcontexts/<bc>/invariants/<invariant>\` |
| Attribute | \`<owner path>/attributes/<attribute>\` (owner is an entity, value object or schema) |
| Consumable of an aggregate | \`#/boundedcontexts/<bc>/aggregates/<aggregate>/provides/<consumable>\` |
| Service | \`#/boundedcontexts/<bc>/services/<service>\` |
| Consumable of a service | \`#/boundedcontexts/<bc>/services/<service>/provides/<consumable>\` |
| Policy | \`#/boundedcontexts/<bc>/policies/<policy>\` |
| Process | \`#/boundedcontexts/<bc>/processes/<process>\` |
| Glossary term | \`#/boundedcontexts/<bc>/glossary/<term>\` |
| Schema | \`#/boundedcontexts/<bc>/schemas/<schema>\` |
| Answer an operation returns | \`<operation path>/returns\` |
| Answer an operation rejects with | \`<operation path>/rejects/<schema>\` |
| Consumption | \`<consumer path>/consumes/<consumable path, with ~ for />\`, plus \`/<id of the first caller in by>\` where the consumer takes that consumable more than once |
| Relationship | \`#/relationships/<source>~<type>~<target>\` |

A consumption has no id of its own, so its path is derived from the pair it joins: \`#/boundedcontexts/sales/services/order_app/consumes/boundedcontexts~catalog~services~pet_app~provides~get_pet\` is Order App's consumption of Pet App's Get Pet. It is never the position in \`consumes[]\`, so reordering the array changes no ref, and it is computed rather than stored, so nothing writes it in a file: it is what a diagnostic about a consumption points at. One consumer may take one consumable more than once when the exchanges differ — an archive keeping the response as it stands, a decision translating it through an anti-corruption layer — and the pair alone then no longer identifies a consumption: each of them names the callers that make it, no two of them name the same caller (\`consumption-once\`), and the id of the first caller in \`by\` is appended as a further segment. A pair declared once keeps the plain ref.

A relationship has no id of its own either: its path is the two contexts it joins and the type that joins them, so \`#/relationships/catalog_bc~customer-supplier~sales_bc\` is the customer-supplier relationship from Catalog to Sales. It too is computed rather than stored, and it is what a diagnostic about a relationship points at.

An answer has no id of its own either: it is one operation coming back, so its path is that operation's plus what it came back as. \`#/boundedcontexts/payments/services/payments_api/provides/authorise_payment/rejects/payment_declined\` is what AuthorisePayment refuses with, and the same path ending \`/returns\` is what it answers with when it succeeds. A reaction waiting on an answer names it this way and never by the schema alone: schemas are shared, so two operations may refuse with one shape, and the shape alone cannot say which call came back. The schema id in a \`/rejects/\` path is one the operation declares in \`rejects\`; anything else resolves to nothing.

A bounded context path never embeds the domain or subdomain, so moving a context between subdomains breaks no refs. A ref that points at nothing makes the whole file fail to load.
`;

export function renderModelReference(): string {
	const schema: JsonSchema = require(
		join(corePkg, "dist/workspace.schema.json"),
	);
	const defs = (
		schema as unknown as { definitions: Record<string, JsonSchema> }
	).definitions;
	const parts: string[] = [
		GENERATED_HEADER("dist/workspace.schema.json"),
		"# ODS model reference",
		"",
		"The complete shape of a workspace file. Collections keyed by id are JSON objects whose keys are the element ids; `array of` collections are JSON arrays. Required fields must be present even when empty (`{}` or `[]`).",
		"",
		renderObject("Workspace", schema, defs),
	];
	for (const [name, def] of Object.entries(defs)) {
		if (def.enum) continue; // enums are inlined where they are used
		parts.push(renderObject(name.replace(/Schema$/, ""), def, defs));
	}
	parts.push(REF_GRAMMAR);
	return parts.join("\n");
}

// ---------------------------------------------------------------------------
// validation-rules.md
// ---------------------------------------------------------------------------

export function renderValidationRules(): string {
	const { RULE_CATALOG } = require("@open-domain-specification/core") as {
		RULE_CATALOG: ReadonlyArray<{
			rule: string;
			severities: string[];
			summary: string;
			why: string;
			fix: string;
		}>;
	};
	const parts: string[] = [
		GENERATED_HEADER("RULE_CATALOG"),
		"# Validation rules",
		"",
		"`Workspace.validate()` returns diagnostics `{ severity, rule, message, ref }`. Errors describe a model that contradicts itself and should be fixed before finishing. Warnings describe a decision that is missing; discuss them with the user rather than silently fixing them. Explain a diagnostic to the user in the plain words below, not by quoting the rule id.",
		"",
	];
	for (const r of RULE_CATALOG) {
		parts.push(
			`## \`${r.rule}\` (${r.severities.join(", ")})`,
			"",
			`**Requires:** ${r.summary}`,
			"",
			`**Why it matters:** ${r.why}`,
			"",
			`**Usual fix:** ${r.fix}`,
			"",
		);
	}
	return parts.join("\n");
}

// ---------------------------------------------------------------------------
// strategic-relationships.md
// ---------------------------------------------------------------------------

const CATEGORY_HEADINGS: Array<[string, string, string]> = [
	[
		"relationship",
		"Relationship types",
		"The `type` of a context relationship. Exactly one per relationship.",
	],
	[
		"upstream-role",
		"Upstream roles",
		"How the upstream side exposes what it provides: a relationship's `upstreamRoles`, and a consumable's `pattern`.",
	],
	[
		"downstream-role",
		"Downstream roles",
		"How the downstream side protects itself: a relationship's `downstreamRoles`, and a consumption's `pattern`.",
	],
];

export function renderStrategicRelationships(): string {
	const { PATTERNS } = require("@open-domain-specification/core") as {
		PATTERNS: Record<
			string,
			{
				name: string;
				abbreviation: string;
				category: string;
				summary: string;
				architecturalNature: string;
				tradeOffs: string[];
			}
		>;
	};
	const parts: string[] = [
		GENERATED_HEADER("PATTERNS"),
		"# Strategic relationships",
		"",
		"What each strategic pattern means. Explain one to the user in these words: the diagram legend, the hover summaries and the generated documentation all read the same table, so your explanation and what they are looking at agree. The value in the left column is what goes in the model.",
		"",
	];
	for (const [category, heading, blurb] of CATEGORY_HEADINGS) {
		parts.push(`## ${heading}`, "", blurb, "");
		for (const [key, pattern] of Object.entries(PATTERNS)) {
			if (pattern.category !== category) continue;
			parts.push(
				`### \`${key}\` — ${pattern.name} (${pattern.abbreviation})`,
				"",
				pattern.summary,
				"",
				pattern.architecturalNature,
				"",
				...pattern.tradeOffs.map((t) => `- ${t}`),
				"",
			);
		}
	}
	return parts.join("\n");
}

export function generateReferences(): Array<{ path: string; content: string }> {
	return [
		{ path: "references/model-reference.md", content: renderModelReference() },
		{
			path: "references/validation-rules.md",
			content: renderValidationRules(),
		},
		{
			path: "references/strategic-relationships.md",
			content: renderStrategicRelationships(),
		},
	];
}

export function writeReferences(): void {
	for (const file of generateReferences())
		writeFileSync(join(skillRoot, file.path), file.content, "utf8");
}

// ---------------------------------------------------------------------------
// bundle.generated.ts
// ---------------------------------------------------------------------------

function walk(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
		const full = join(dir, entry.name);
		return entry.isDirectory() ? walk(full) : [full];
	});
}

export function readBundle(): Array<{ path: string; content: string }> {
	return walk(skillRoot)
		.map((full) => ({
			path: relative(skillRoot, full).split("\\").join("/"),
			content: readFileSync(full, "utf8"),
		}))
		.sort((a, b) => a.path.localeCompare(b.path));
}

export function writeBundle(): void {
	const version: string = require(join(packageRoot, "package.json")).version;
	const files = readBundle();
	const body = [
		"// Generated by scripts/generate.mts; do not edit.",
		`export const SKILL_VERSION = ${JSON.stringify(version)};`,
		"export const BUNDLE: ReadonlyArray<{ path: string; content: string }> = [",
		...files.map(
			(f) =>
				`\t{ path: ${JSON.stringify(f.path)}, content: ${JSON.stringify(f.content)} },`,
		),
		"];",
		"",
	].join("\n");
	writeFileSync(join(packageRoot, "src/bundle.generated.ts"), body, "utf8");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	writeReferences();
	writeBundle();
	console.log("skill: references and bundle generated");
}
