/**
 * Build-time generation for the skill bundle.
 *
 * - `generateReferences()` renders `references/model-reference.md` and
 *   `references/validation-rules.md` from the core package's build output, so
 *   the skill can never describe a model that core does not implement.
 * - `writeBundle()` embeds every file under `skill/` into
 *   `src/bundle.generated.ts`, so consumers (the VS Code extension included)
 *   read the bundle from the library without touching node_modules.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
export const packageRoot = join(here, "..");
export const skillRoot = join(packageRoot, "skill");

const corePkg = dirname(
	require.resolve("@open-domain-specification/core/package.json"),
);
// No version in the header: the build must leave the committed files untouched
// across a version bump, or lerna refuses to publish on a dirty tree.
const GENERATED_HEADER = (source: string) =>
	`<!-- Generated by packages/skill/scripts/generate.mts from @open-domain-specification/core (${source}); do not edit. -->\n`;

// ---------------------------------------------------------------------------
// model-reference.md
// ---------------------------------------------------------------------------

type JsonSchema = {
	title?: string;
	description?: string;
	type?: string;
	enum?: string[];
	properties?: Record<string, JsonSchema>;
	required?: string[];
	items?: JsonSchema | JsonSchema[];
	additionalProperties?: boolean | JsonSchema;
	anyOf?: JsonSchema[];
	$ref?: string;
};

function refName(ref: string): string {
	return ref.replace("#/definitions/", "");
}

function isRefObject(schema: JsonSchema): boolean {
	return (
		schema.type === "object" &&
		!!schema.properties &&
		Object.keys(schema.properties).length === 1 &&
		"$ref" in schema.properties
	);
}

/** A compact type expression for one property. */
function typeOf(schema: JsonSchema, defs: Record<string, JsonSchema>): string {
	if (schema.$ref) {
		const name = refName(schema.$ref);
		const target = defs[name];
		if (target?.enum) return target.enum.map((v) => `"${v}"`).join(" | ");
		const shown = name.replace(/Schema$/, "");
		return `[${shown}](#${shown.toLowerCase()})`;
	}
	if (schema.enum) return schema.enum.map((v) => `"${v}"`).join(" | ");
	if (schema.anyOf) return schema.anyOf.map((s) => typeOf(s, defs)).join(" | ");
	if (isRefObject(schema)) return '`{ "$ref": string }`';
	// A tuple — `[{ $ref }, { $ref }]`, which is what a symmetric
	// relationship's `participants` is — comes out of the JSON schema with
	// `items` as an array, one entry per position. Read as a single item
	// schema it had no `type` and rendered "array of unknown", so the one
	// field that says a partnership has exactly two ends said nothing at all.
	if (schema.type === "array" && Array.isArray(schema.items))
		return `[${schema.items.map((s) => typeOf(s, defs)).join(", ")}]`;
	if (schema.type === "array")
		return `array of ${typeOf((schema.items as JsonSchema) ?? {}, defs)}`;
	if (
		schema.type === "object" &&
		schema.additionalProperties &&
		typeof schema.additionalProperties === "object"
	)
		return `map of id to ${typeOf(schema.additionalProperties, defs)}`;
	return schema.type ?? "unknown";
}

function oneLine(text?: string): string {
	return (text ?? "").replace(/\s*\n\s*/g, " ").trim();
}

function renderObject(
	name: string,
	schema: JsonSchema,
	defs: Record<string, JsonSchema>,
): string {
	const lines: string[] = [`## ${name}`, ""];
	if (schema.description) lines.push(oneLine(schema.description), "");
	if (schema.anyOf) {
		lines.push(
			`One of: ${schema.anyOf.map((s) => typeOf(s, defs)).join(", ")}.`,
			"",
		);
		return lines.join("\n");
	}
	const required = new Set(schema.required ?? []);
	lines.push("| Field | Type | Required | Notes |", "|---|---|---|---|");
	for (const [field, prop] of Object.entries(schema.properties ?? {})) {
		lines.push(
			`| \`${field}\` | ${typeOf(prop, defs)} | ${required.has(field) ? "yes" : "no"} | ${oneLine(prop.description)} |`,
		);
	}
	lines.push("");
	if (schema.additionalProperties === false)
		lines.push("No other fields are allowed.", "");
	return lines.join("\n");
}

const REF_GRAMMAR = `## Ref grammar

Every cross-link is an object \`{ "$ref": "<path>" }\`. Refs are canonical model paths; derived answers, relationships and consumptions below are computed identities rather than literal JSON property paths. An id and the segment that carries it in a ref are two representations of the same identity. JSON object keys and explicit DSL \`id\` values are the raw authored ids; keep them verbatim. In a ref, encode each complete raw id as one JSON Pointer segment: write \`~\` as \`~0\`, then \`/\` as \`~1\`. The grammar below writes that operation as \`E(id)\`. For example, raw id \`charges/a~b\` is the single segment \`charges~1a~0b\`; raw id \`charges~1a~0b\` is the distinct segment \`charges~01a~00b\`.

Do not pre-encode JSON keys or DSL ids. Every string id, including an explicit empty id and every Unicode spelling, is preserved exactly; ids are not trimmed, case-folded, normalised or silently replaced by a name-derived id. When one complete ref is embedded inside another ref, as consumptions do, encode the complete nested ref once more as one segment. Percent encoding in a URL fragment and filename encoding in generated Markdown are transport concerns, not part of this model grammar.

| Element | Path |
|---|---|
| Team | \`#/teams/E(team)\` |
| Domain | \`#/domains/E(domain)\` |
| Subdomain | \`#/domains/E(domain)/subdomains/E(subdomain)\` |
| Bounded context | \`#/boundedcontexts/E(bc)\` |
| Aggregate | \`#/boundedcontexts/E(bc)/aggregates/E(aggregate)\` |
| Entity | \`#/boundedcontexts/E(bc)/aggregates/E(aggregate)/entities/E(entity)\` |
| Value object | \`#/boundedcontexts/E(bc)/valueobjects/E(valueobject)\` |
| Invariant of an aggregate | \`#/boundedcontexts/E(bc)/aggregates/E(aggregate)/invariants/E(invariant)\` |
| Invariant of a value object | \`#/boundedcontexts/E(bc)/valueobjects/E(valueobject)/invariants/E(invariant)\` |
| Invariant of a context | \`#/boundedcontexts/E(bc)/invariants/E(invariant)\` |
| Attribute | \`<owner path>/attributes/E(attribute)\` (owner is an entity, value object or schema) |
| Consumable of an aggregate | \`#/boundedcontexts/E(bc)/aggregates/E(aggregate)/provides/E(consumable)\` |
| Service | \`#/boundedcontexts/E(bc)/services/E(service)\` |
| Consumable of a service | \`#/boundedcontexts/E(bc)/services/E(service)/provides/E(consumable)\` |
| Policy | \`#/boundedcontexts/E(bc)/policies/E(policy)\` |
| Process | \`#/boundedcontexts/E(bc)/processes/E(process)\` |
| Process deadline | \`#/boundedcontexts/E(bc)/processes/E(process)/deadlines/E(deadline)\` |
| Glossary term | \`#/boundedcontexts/E(bc)/glossary/E(term)\` |
| Schema | \`#/boundedcontexts/E(bc)/schemas/E(schema)\` |
| Answer an operation returns | \`<operation path>/returns\` |
| Answer an operation completes with, where it returns nothing | \`<operation path>/completed\` |
| Answer an operation rejects with | \`<operation path>/rejects/E(schema bc)/E(schema)\` |
| Answer for one enumerated reason of that refusal | \`<operation path>/rejects/E(schema bc)/E(schema)/E(reason)\` |
| Consumption | \`<consumer path>/consumes/E(<full consumable path>)\`, plus \`/by/E(<full first caller path>)\` where the consumer takes that consumable more than once |
| Relationship | \`#/relationships/E(source)/<type>/E(target)\`, plus \`/E(name in snake case)\` where the agreement carries a name |

A consumption has no id of its own, so its path is derived from the pair it joins: \`#/boundedcontexts/sales/services/order_app/consumes/#~1boundedcontexts~1catalog~1services~1pet_app~1provides~1get_pet\` is Order App's consumption of Pet App's Get Pet. The consumable's complete canonical ref, including its leading \`#/\`, is embedded as one segment, so its slashes and any tildes already escaped inside it are escaped once more. It is never the position in \`consumes[]\`, so reordering the array changes no ref, and it is computed rather than stored, so nothing writes it in a file: it is what a diagnostic about a consumption points at. One consumer may take one consumable more than once when the exchanges differ — an archive keeping the response as it stands, a decision translating it through an anti-corruption layer — and the pair alone then no longer identifies a consumption: each of them names the callers that make it, no two of them name the same caller (\`consumption-once\`), and \`/by/E(<full first caller ref>)\` is appended. The full caller ref includes its context and owner, so callers with the same local id remain distinct. A pair declared once keeps the plain ref.

A relationship has no id of its own either: its path is the two contexts it joins and the type that joins them, so \`#/relationships/catalog_bc/customer-supplier/sales_bc\` is the customer-supplier relationship from Catalog to Sales. It too is computed rather than stored, and it is what a diagnostic about a relationship points at. One pair may hold two agreements in one direction — a negotiated fulfilment API and a tolerated legacy feed from the same warehouse — and each of those carries a \`name\`, whose snake-case identity is appended as one encoded segment: \`#/relationships/warehouse_bc/upstream-downstream/sales_bc/legacy_feed\`. Two agreements between one pair in one direction that are both unnamed, or that share a name, are one declaration made twice, and \`relationship-duplicate\` refuses them. Source order and the existing symmetric-relationship duplicate semantics do not change.

An answer has no id of its own either: it is one operation coming back, so its path is that operation's complete canonical ref plus what it came back as. \`#/boundedcontexts/payments/services/payments_api/provides/authorise_payment/rejects/payments/payment_declined\` is what AuthorisePayment refuses with, and the same operation path ending \`/returns\` is what it answers with when it succeeds. A reaction waiting on an answer names it this way and never by the schema alone: schemas are shared, so two operations may refuse with one shape, and the shape alone cannot say which call came back. A \`/rejects/\` path names the shape by its bounded context and its id, because an id is unique only inside its own context. The shape is one the operation declares in \`rejects\`; anything else resolves to nothing. Where that refusal enumerates \`reasons\`, one of them may be named in a further segment — \`.../rejects/payment_provider/provider_decline/issuer_unavailable\` — which waits on that outcome alone, while the path without it waits on every refusal of that shape. An empty reason is no reason and names the shape-level refusal; an empty id is still an id segment.

Encoding every authored id in the operation prefix makes the answer grammar injective. In context \`b\`, service \`h\`, operation A with id \`a\` may reject schema \`decline\` for reason \`completed\`; its answer is \`#/boundedcontexts/b/services/h/provides/a/rejects/b/decline/completed\`. A distinct operation B whose raw id is \`a/rejects/b/decline\` has ref \`#/boundedcontexts/b/services/h/provides/a~1rejects~1b~1decline\`, so B's completion is \`.../a~1rejects~1b~1decline/completed\` and cannot equal A's refusal. Unknown shapes or reasons, malformed escapes, noncanonical unescaped forms and surplus segments resolve to nothing. There are no legacy aliases.

A bounded context path never embeds the domain or subdomain, so moving a context between subdomains breaks no refs. A ref that points at nothing is an \`unresolved-ref\` diagnostic at the referencing element; the rest of the file still loads. Canonical refs are model identity strings. When a surface puts one in a URL fragment, a Markdown filename or another transport, that surface encodes and decodes the transport layer separately without changing the canonical ref.

## Refs between files

A folder of workspace files is a set: every file is one complete workspace with an id of its own, and there is no root file or manifest that lists them. A ref that begins with \`#/\` is local: it is looked up in the file that writes it and nowhere else, so the same local id may be used in two files and each file's refs mean its own. A ref that reaches another file writes that file's path first and the same pointer after it, with no extra \`#\`: \`ledger.json#/boundedcontexts/ledger/aggregates/account\`.

\`\`\`
Ref          ::= LocalRef | QualifiedRef
LocalRef     ::= "#/" Pointer
QualifiedRef ::= WirePath "#/" Pointer
WirePath     ::= Segment ( "/" Segment )*
Segment      ::= "." | ".." | ( unreserved | "%" HEX HEX )+     ; unreserved = A-Z a-z 0-9 - . _ ~
\`\`\`

- The path is relative to the file that writes the ref, with forward slashes. Each file name is written percent-encoded as UTF-8, with uppercase hex: a file \`my team.json\` is \`my%20team.json\`, \`a#%.json\` is \`a%23%25.json\` and \`team/ü.json\` is \`team/%C3%BC.json\`. A raw space, a raw non-ASCII character, a backslash, a colon, a query or a malformed \`%\` is not in the grammar. No normalisation of case or Unicode form is applied.
- \`.\` and \`..\` are folded against the writing file's directory, and \`..\` is allowed exactly when the result stays inside the set's root, the folder the host opened (the \`.ods\` folder, the folder an upload was taken from, the explicit root of a viewer URL). A path that leaves the root, is absolute, names a URL, is empty, has an empty segment, does not end in \`.json\` or names \`schema.json\` resolves to nothing. Nothing is read above the root.
- A qualified ref is looked up in exactly the file it names, and it must be a kind of element the field can hold, as a local one must. It fails four ways, each an \`unresolved-ref\` at the element that wrote it, with the cause in the message: the path is invalid, the file is not in the set, the file has no such element, or the element is the wrong kind for the field. Opening one file alone gives every qualified ref the cause "no such file", because there is no set to look in; open the folder instead.
- What is allowed to cross a file is exactly what is allowed to cross a context. A file boundary grants no permission and removes none: the same relationship, shared kernel, conformist or customer-supplier route that lets a context name another's value object, schema, consumable or identity in one file lets it do so across two, and the rules that refuse it in one file refuse it across two. Where two contexts are in different files, the relationship that permits the crossing may be declared in either file; rules read every file of the set.
- Files may refer to each other in both directions. A cycle of files is not diagnosed; a cycle the model forbids (a relationship cycle, a specialisation cycle, a reaction cycle) is diagnosed wherever its links are, in whichever files.
- An element's identity in a set is its file's wire path followed by its local ref, for example \`a%23%25.json#/boundedcontexts/ledger\`. It depends on the file alone: adding, removing or reordering other files never changes it, and two files' \`#/boundedcontexts/ledger\` stay two elements. Hosts that show several workspaces key, link and route by this identity.
- Each file keeps its own \`options\`: an opt-in rule such as \`comments-required\` asks only of the file that sets it.
- A ref in a list that is the pair it joins (a consumer's \`consumes\`, a workspace's \`relationships\`, an entity's or value object's \`relations\`, and a consumption's \`by\`) cannot leave a half-entry behind when what it names is missing. If the ref has a path in front of its \`#\`, whatever becomes of it (an invalid path, a file that is not there, no such element, the wrong kind), the whole entry is kept as written, with every key it had, at the position it had, and is written back untouched; it links again as soon as the file and element are there. If it is a local ref that names nothing, the entry is dropped and reported, and a save drops it, the cost decision 29 names. The same applies to an unknown key on an entry that does resolve: it is dropped and reported by \`unknown-field\`.
- Raw JSON is not trusted to be a workspace. The loader takes a \`WorkspaceSchema\`: a file that is not JSON, or is JSON of another shape, can make it throw, so a host checks the shape of what it hands the loader and reports a file it cannot load as a problem of that file, leaving the rest of the set loaded.
`;

export function renderModelReference(): string {
	const schema: JsonSchema = require(
		join(corePkg, "dist/workspace.schema.json"),
	);
	const defs = (
		schema as unknown as { definitions: Record<string, JsonSchema> }
	).definitions;
	const parts: string[] = [
		GENERATED_HEADER("dist/workspace.schema.json"),
		"# ODS model reference",
		"",
		"The complete shape of a workspace file. Collections keyed by id are JSON objects whose keys are the element ids; `array of` collections are JSON arrays. Required fields must be present even when empty (`{}` or `[]`).",
		"",
		renderObject("Workspace", schema, defs),
	];
	for (const [name, def] of Object.entries(defs)) {
		if (def.enum) continue; // enums are inlined where they are used
		parts.push(renderObject(name.replace(/Schema$/, ""), def, defs));
	}
	parts.push(REF_GRAMMAR);
	return parts.join("\n");
}

// ---------------------------------------------------------------------------
// validation-rules.md
// ---------------------------------------------------------------------------

export function renderValidationRules(): string {
	type Described = ReadonlyArray<{
		rule: string;
		severities: string[];
		summary: string;
		why: string;
		fix: string;
	}>;
	const { RULE_CATALOG, SET_RULE_CATALOG } =
		require("@open-domain-specification/core") as {
			RULE_CATALOG: Described;
			SET_RULE_CATALOG: Described;
		};
	const parts: string[] = [
		GENERATED_HEADER("RULE_CATALOG and SET_RULE_CATALOG"),
		"# Validation rules",
		"",
		"`Workspace.validate()` returns diagnostics `{ severity, rule, message, ref }`. `WorkspaceSet.validate()` returns the same for a folder of files together, each with the `file` it is about; a workspace that belongs to a set is judged with the whole set, since a rule about one file may need what another declares, and one read alone is judged alone. Errors describe a model that contradicts itself and should be fixed before finishing. Warnings describe a decision that is missing; discuss them with the user rather than silently fixing them. Explain a diagnostic to the user in the plain words below, not by quoting the rule id.",
		"",
	];
	const entry = (r: Described[number]) =>
		parts.push(
			`## \`${r.rule}\` (${r.severities.join(", ")})`,
			"",
			`**Requires:** ${r.summary}`,
			"",
			`**Why it matters:** ${r.why}`,
			"",
			`**Usual fix:** ${r.fix}`,
			"",
		);
	for (const r of RULE_CATALOG) entry(r);
	parts.push(
		"# Rules about a folder of files",
		"",
		"The next rules are asked of a set of workspace files, not of one workspace: a workspace alone has no sibling file to share an id with and no host to offer it a path. `WorkspaceSet.validate()` reports them, and every other rule above is asked of the files together.",
		"",
	);
	for (const r of SET_RULE_CATALOG) entry(r);
	return parts.join("\n");
}

// ---------------------------------------------------------------------------
// strategic-relationships.md
// ---------------------------------------------------------------------------

const CATEGORY_HEADINGS: Array<[string, string, string]> = [
	[
		"relationship",
		"Relationship types",
		"The `type` of a context relationship. Exactly one per relationship.",
	],
	[
		"upstream-role",
		"Upstream roles",
		"How the upstream side exposes what it provides: a relationship's `upstreamRoles`, and a consumable's `pattern`.",
	],
	[
		"downstream-role",
		"Downstream roles",
		"How the downstream side protects itself: a relationship's `downstreamRoles`, and a consumption's `pattern`.",
	],
];

export function renderStrategicRelationships(): string {
	const { PATTERNS } = require("@open-domain-specification/core") as {
		PATTERNS: Record<
			string,
			{
				name: string;
				abbreviation: string;
				category: string;
				summary: string;
				architecturalNature: string;
				tradeOffs: string[];
			}
		>;
	};
	const parts: string[] = [
		GENERATED_HEADER("PATTERNS"),
		"# Strategic relationships",
		"",
		"What each strategic pattern means. Explain one to the user in these words: the diagram legend, the hover summaries and the generated documentation all read the same table, so your explanation and what they are looking at agree. The value in the left column is what goes in the model.",
		"",
	];
	for (const [category, heading, blurb] of CATEGORY_HEADINGS) {
		parts.push(`## ${heading}`, "", blurb, "");
		for (const [key, pattern] of Object.entries(PATTERNS)) {
			if (pattern.category !== category) continue;
			parts.push(
				`### \`${key}\` — ${pattern.name} (${pattern.abbreviation})`,
				"",
				pattern.summary,
				"",
				pattern.architecturalNature,
				"",
				...pattern.tradeOffs.map((t) => `- ${t}`),
				"",
			);
		}
	}
	return parts.join("\n");
}

export function generateReferences(): Array<{ path: string; content: string }> {
	return [
		{ path: "references/model-reference.md", content: renderModelReference() },
		{
			path: "references/validation-rules.md",
			content: renderValidationRules(),
		},
		{
			path: "references/strategic-relationships.md",
			content: renderStrategicRelationships(),
		},
	];
}

export function writeReferences(): void {
	for (const file of generateReferences())
		writeFileSync(join(skillRoot, file.path), file.content, "utf8");
}

// ---------------------------------------------------------------------------
// bundle.generated.ts
// ---------------------------------------------------------------------------

function walk(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
		const full = join(dir, entry.name);
		return entry.isDirectory() ? walk(full) : [full];
	});
}

export function readBundle(): Array<{ path: string; content: string }> {
	return walk(skillRoot)
		.map((full) => ({
			path: relative(skillRoot, full).split("\\").join("/"),
			content: readFileSync(full, "utf8"),
		}))
		.sort((a, b) => a.path.localeCompare(b.path));
}

export function writeBundle(): void {
	const version: string = require(join(packageRoot, "package.json")).version;
	const files = readBundle();
	const body = [
		"// Generated by scripts/generate.mts; do not edit.",
		`export const SKILL_VERSION = ${JSON.stringify(version)};`,
		"export const BUNDLE: ReadonlyArray<{ path: string; content: string }> = [",
		...files.map(
			(f) =>
				`\t{ path: ${JSON.stringify(f.path)}, content: ${JSON.stringify(f.content)} },`,
		),
		"];",
		"",
	].join("\n");
	writeFileSync(join(packageRoot, "src/bundle.generated.ts"), body, "utf8");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	writeReferences();
	writeBundle();
	console.log("skill: references and bundle generated");
}
