// The checker against records written by the real runners, not by replaying
// their events: a real Mocha (the one @vscode/test-cli bundles) through the
// results reporter, and a real Playwright through its JSON reporter.
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import {
	checkResults,
	classifyPlaywrightTest,
	playwrightTests,
} from "./check-real-host-results.mjs";

const require = createRequire(import.meta.url);
const tmp = mkdtempSync(join(tmpdir(), "ods-real-runners-"));
const GOOD_KEYBOARD = {
	suites: [
		{
			specs: [
				{
					title: "t",
					tests: [
						{
							status: "expected",
							expectedStatus: "passed",
							results: [{ status: "passed" }],
						},
					],
				},
			],
		},
	],
};

describe("a real Mocha run through the results reporter", () => {
	const reporter = join(
		import.meta.dirname,
		"../apps/ods-vscode/src/test/results-reporter.cjs",
	);
	const runner = join(import.meta.dirname, "fixtures/mocha-outcomes/run.cjs");
	const record = (scenario) => {
		const output = join(tmp, `mocha-${scenario}.json`);
		spawnSync(process.execPath, [runner, reporter, output], {
			env: { ...process.env, ODS_SCENARIO: scenario },
			encoding: "utf8",
		});
		return JSON.parse(readFileSync(output, "utf8"));
	};
	const check = (report) =>
		checkResults({
			vscode: { fixture: report },
			keyboard: GOOD_KEYBOARD,
			configs: ["fixture"],
			allowedSkips: {},
		});

	it("accepts a clean pass", () => {
		const report = record("clean");
		expect(report.passes).toMatchObject([
			{ fullTitle: "fixture a clean pass", retries: 0 },
		]);
		expect(report.retried).toEqual([]);
		const r = check(report);
		expect(r.problems).toEqual([]);
		expect(r.ok).toBe(true);
	});

	it("rejects a test that passed only on its retry, naming the config and the test", () => {
		const report = record("retried");
		// The reporter saw what Mocha emitted: a retry event, then a pass on retry 1.
		expect(report.retried.map((r) => r.fullTitle)).toEqual([
			"fixture passes only on its retry",
		]);
		expect(report.failures).toEqual([]);
		expect(
			report.passes.find((p) => p.title === "passes only on its retry").retries,
		).toBe(1);
		const r = check(report);
		expect(r.ok).toBe(false);
		expect(r.problems).toEqual([
			"vscode-test fixture: passed only after a retry: fixture passes only on its retry",
		]);
		expect(r.summary.vscode.fixture).toMatchObject({
			executed: 2,
			passed: 1,
			failed: 1,
		});
	});

	it("rejects a test that fails every attempt", () => {
		const r = check(record("failing"));
		expect(r.ok).toBe(false);
		expect(r.problems).toEqual([
			"vscode-test fixture: failed: fixture fails every attempt",
		]);
	});

	it("rejects a record it does not recognise rather than counting it", () => {
		for (const bad of [
			{ passes: [{ fullTitle: "x", retries: 0 }], pending: [], failures: [] },
			{ passes: [{ fullTitle: "x" }], pending: [], failures: [], retried: [] },
			{ passes: "x", pending: [], failures: [], retried: [] },
		]) {
			const r = check(bad);
			expect(r.ok).toBe(false);
			expect(r.problems[0]).toContain("unrecognised results file");
		}
	});
});

describe("a real Playwright run through its JSON reporter", () => {
	let report;
	beforeAll(() => {
		// Generated by @playwright/test (the version in package-lock.json) from
		// fixtures/playwright-outcomes; no browser is involved.
		const output = join(tmp, "playwright.json");
		spawnSync(
			process.execPath,
			[
				require.resolve("@playwright/test/cli"),
				"test",
				"-c",
				join(
					import.meta.dirname,
					"fixtures/playwright-outcomes/playwright.config.mjs",
				),
			],
			{
				encoding: "utf8",
				env: { ...process.env, PLAYWRIGHT_JSON_OUTPUT_NAME: output },
			},
		);
		report = JSON.parse(readFileSync(output, "utf8"));
	}, 60_000);

	const kinds = () =>
		Object.fromEntries(
			playwrightTests(report).map((t) => [t.title, classifyPlaywrightTest(t)]),
		);

	it("reports a test.fail() test that fails as an expected outcome, which is what the checker must see through", () => {
		const t = playwrightTests(report).find((x) =>
			x.title.includes("test.fail()"),
		);
		expect(t.status).toBe("expected");
		expect(t.expectedStatus).toBe("failed");
		expect(t.results[0].status).toBe("failed");
	});

	it("classifies each outcome", () => {
		expect(Object.values(kinds()).sort()).toEqual([
			"expected-failure",
			"failed",
			"passed",
			"skipped",
		]);
	});

	it("accepts the pass, and rejects the failure, the expected failure and the fixme, naming each", () => {
		const r = checkResults({
			vscode: {},
			keyboard: report,
			configs: [],
			allowedSkips: {},
		});
		expect(r.ok).toBe(false);
		expect(r.summary.keyboard).toMatchObject({
			passed: 1,
			failed: 1,
			other: 1,
			skipped: 1,
		});
		expect(r.problems.filter((p) => p.startsWith("keyboard:")).sort()).toEqual(
			[
				"keyboard: an expected failure (test.fail) is not a pass: outcomes.pw.mjs > an expected failure that fails, as test.fail() declares",
				"keyboard: failed: outcomes.pw.mjs > an ordinary failing test",
				"keyboard: unexpected skip: outcomes.pw.mjs > a fixme test",
			].sort(),
		);
		expect(r.problems.join("\n")).not.toContain("an ordinary passing test");
	});

	it("accepts a report that holds only the passing test", () => {
		const only = structuredClone(report);
		const spec = only.suites[0].specs.find(
			(s) => s.title === "an ordinary passing test",
		);
		only.suites[0].specs = [spec];
		const r = checkResults({
			vscode: {},
			keyboard: only,
			configs: [],
			allowedSkips: {},
		});
		expect(r.problems).toEqual([]);
		expect(r.summary.keyboard).toMatchObject({ executed: 1, passed: 1 });
	});

	it("rejects a passing test whose results are missing, or whose status is unrecognised", () => {
		const mutate = (change) => {
			const only = structuredClone(report);
			const spec = only.suites[0].specs.find(
				(s) => s.title === "an ordinary passing test",
			);
			change(spec.tests[0]);
			only.suites[0].specs = [spec];
			return checkResults({
				vscode: {},
				keyboard: only,
				configs: [],
				allowedSkips: {},
			});
		};
		expect(
			mutate((t) => {
				t.results = undefined;
			}).problems.join(),
		).toContain("unrecognised result");
		expect(
			mutate((t) => {
				t.results = [];
			}).ok,
		).toBe(false);
		expect(
			mutate((t) => {
				t.results[0].status = "failed";
			}).ok,
		).toBe(false);
		expect(
			mutate((t) => {
				t.status = "weird";
			}).ok,
		).toBe(false);
		expect(
			mutate((t) => {
				t.expectedStatus = "timedOut";
			}).ok,
		).toBe(false);
		expect(
			mutate((t) => {
				t.expectedStatus = "failed";
			}).ok,
		).toBe(false);
		expect(
			mutate((t) => {
				t.results.push({ status: "passed" });
			}).problems.join(),
		).toContain("flaky");
	});
});
